version: '3.9'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      db:
        condition: service_healthy  
  db:
    image: mongo:4.2
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5  
  nginx:
    build: 
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  mongo-data:
