version: '3.9'
services:
  app: 
    image: 644435390668.dkr.ecr.eu-west-2.amazonaws.com/guy-repo:${New_tag} 
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy  
  db:
    build: 
      context: .
      dockerfile: mongo-db.dockerfile
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass  
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5  
  nginx:
    build: 
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./templates:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro  

volumes:
  mongo-data:
